[package]
name = "chronotrinite"
version = "0.1.2"
description = "Neutrinite DeVeFi Chronotrinite"
repository = "https://github.com/Neutrinomic/devefi_chronotrinite"
keywords = [ ]
license = ""

[dependencies]
base = "0.13.2"
stableheapbtreemap = "1.5.0"
vector = "0.4.1"
mosup = "0.1.1"
swbstable = "1.1.1"
map = "9.0.1"